steps:

- name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
  - -exc
  - |
    docker pull gcr.io/$_STAGING_PROJECT_ID/testrunner:sha_$COMMIT_SHA
    docker tag  gcr.io/$_STAGING_PROJECT_ID/testrunner:sha_$COMMIT_SHA gcr.io/$PROJECT_ID/testrunner:$TAG_NAME

images:
- gcr.io/$P}ROJECT_ID/testrunner:$TAG_NAME
